version: '3.1'
services:
  app:
    image: 'calculator:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    networks:
      - spring-calculator

networks:
  spring-calculator:
