name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run unit tests
        run: mvn test
      - name: Build Jar file
        run: ./calculator build-jar
      - name: Save Jar file
        uses: actions/upload-artifact@v3
        with:
          name: calculator-0.0.1-SNAPSHOT
          path: target/calculator-0.0.1-SNAPSHOT.jar
          retention-days: 1
      - name: Generate report file
        run: ./calculator prepare-report
      - name: Save generated report file
        uses: actions/upload-artifact@v3
        with:
          name: report-file
          path: dist/calculator-report.tar.gz
          retention-days: 1
      - name: Generate coverage report
        run: ./calculator test-coverage-report
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage-report
          path: dist/unit-test-coverage.tar.gz
          retention-days: 1
